name: Dispatch
on:
    pull_request:
        branches: [develop]
        types: [closed]
jobs:
  CanDIG-dispatch:
    runs-on: ubuntu-latest
    env:
      PARENT_REPOSITORY: 'mshadbolt/CanDIGv2'
      CHECKOUT_BRANCH: 'develop'
      PR_AGAINST_BRANCH: 'develop'
      OWNER: 'mshadbolt'
    if: github.event.pull_request.merged == true
    steps:
            - name: Check out repository code
              uses: actions/checkout@v3
            - name: Get PR info
              shell: python
              run: |
                  import json
                  import os
                  import shlex
                  import pprint
                  with open('${{ github.event_path }}') as fh:
                      event = json.load(fh)
                      pprint.pprint(event)
                      escaped = shlex.quote(event['pull_request']['title'])
                      print(escaped)    
                  with open(os.environ['GITHUB_ENV'], 'a') as fh:
                      print(f'PR_TITLE={escaped}', file=fh)
            - name: Create PR in CanDIGv2
              id: make_pr
              uses: CanDIG/github-action-pr-expanded@mshadbolt/sanitize-input
              with:
                  github_token: ${{ secrets.SUBMODULE_PR }}
                  parent_repository: ${{ env.PARENT_REPOSITORY }}
                  checkout_branch: ${{ env.CHECKOUT_BRANCH}}
                  pr_against_branch: ${{ env.PR_AGAINST_BRANCH }}
                  pr_title: "Submodule update from merging: '${{ env.PR_TITLE }}'"
                  pr_description: "PR triggered by update to develop branch on ${{ github.repository }}. Commit hash: `${{ github.sha }}`."
                  owner: ${{ env.OWNER }}
                  submodule_path: lib/candig-ingest/candigv2-ingest
                  label: Submodule update
